//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Branch()
        {
            this.Branch1 = new HashSet<Branch>();
            this.BrandInfoes = new HashSet<BrandInfo>();
        }
    
        public int branchId { get; set; }
        public int brandId { get; set; }
        public Nullable<int> parentId { get; set; }
        public string branchName { get; set; }
        public string code { get; set; }
        public string affiliateTag { get; set; }
        public string location { get; set; }
        public Nullable<byte> language { get; set; }
        public Nullable<byte> timeZone { get; set; }
        public Nullable<bool> enabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Branch> Branch1 { get; set; }
        public virtual Branch Branch2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BrandInfo> BrandInfoes { get; set; }
    }
}
