//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Brand()
        {
            this.tradingServers = new HashSet<TradingServer>();
        }
    
        public int brandId { get; set; }
        public string brandName { get; set; }
        public Nullable<bool> rootEntity { get; set; }
        public Nullable<int> mainBranchId { get; set; }
        public Nullable<int> mainDepartmentId { get; set; }
        public string brandLocation { get; set; }
        public string website { get; set; }
        public Nullable<byte> timeZone { get; set; }
        public Nullable<bool> enabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TradingServer> tradingServers { get; set; }
    }
}
