//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.BrandInfoes = new HashSet<BrandInfo>();
        }
    
        public int departmentId { get; set; }
        public string departmentName { get; set; }
        public int brandId { get; set; }
        public Nullable<int> parentId { get; set; }
        public string parentName { get; set; }
        public Nullable<bool> rootEntity { get; set; }
        public string brandName { get; set; }
        public string branchName { get; set; }
        public Nullable<int> managerId { get; set; }
        public string managerName { get; set; }
        public string description { get; set; }
        public string location { get; set; }
        public Nullable<byte> language { get; set; }
        public Nullable<byte> timeZone { get; set; }
        public Nullable<bool> enabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BrandInfo> BrandInfoes { get; set; }
    }
}
