//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.BrandInfoes = new HashSet<BrandInfo>();
        }
    
        public int userId { get; set; }
        public long memebershipUserId { get; set; }
        public string userName { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string profilePicture { get; set; }
        public string signturePicture { get; set; }
        public string firstName { get; set; }
        public string fullName { get; set; }
        public string lastName { get; set; }
        public string phoneNumber { get; set; }
        public string gender { get; set; }
        public System.DateTime birthday { get; set; }
        public System.DateTime memberSince { get; set; }
        public string location { get; set; }
        public Nullable<int> languageId { get; set; }
        public string languageName { get; set; }
        public Nullable<int> position { get; set; }
        public string job { get; set; }
        public string voIpExtension { get; set; }
        public string voIpSip { get; set; }
        public string promoCode { get; set; }
        public Nullable<bool> depositSmsNotification { get; set; }
        public bool enabled { get; set; }
        public bool isOnline { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BrandInfo> BrandInfoes { get; set; }
    }
}
