//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentUser
    {
        public int departmentId { get; set; }
        public int userId { get; set; }
        public string fullName { get; set; }
        public bool isManager { get; set; }
        public string position { get; set; }
    }
}
